{% set name = "robotframework-seleniumlibrary" %}
{% set version = "6.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef6d5f1b481513cb6e3d15d78b0dcbabc53aa0866d8d23844b899ac824a0ea82

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4
  run:
    - python >=3.6,<4
    - robotframework >=3.1.2
    - robotframework-pythonlibcore >=2.1.0
    - selenium >=3.141.0

test:
  requires:
    - pip
  imports:
    - SeleniumLibrary
  commands:
    - python -m pip check

about:
  home: https://github.com/robotframework/SeleniumLibrary
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - COPYRIGHT.txt
  summary: Web testing library for Robot Framework
  doc_url: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
  dev_url: https://github.com/robotframework/SeleniumLibrary
  description: |
    SeleniumLibrary is a web testing library for Robot Framework that utilizes
    the Selenium tool internally. The project is hosted on GitHub and downloads
    can be found from PyPI.

    SeleniumLibrary works with Selenium 3 and 4. It supports Python 2.7 as well
    as Python 3.6 or newer. In addition to the normal Python interpreter, it works
    also with PyPy and Jython. Unfortunately Selenium is not currently supported
    by IronPython and thus this library does not work with IronPython either.

extra:
  recipe-maintainers:
    - bollwyvl
