{% set name = "robotframework-seleniumlibrary" %}
{% set version = "4.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7004feaa0e0f66013c877470078ea4fa65ac07f65023a95d91c51a9618abbf07

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - selenium >=3.8.1
    - robotframework >=3.0.4

test:
  imports:
    - SeleniumLibrary

about:
  home: https://github.com/robotframework/SeleniumLibrary
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Web testing library for Robot Framework
  doc_url: https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
  dev_url: https://github.com/robotframework/SeleniumLibrary
  description: |
    SeleniumLibrary is a web testing library for Robot Framework that utilizes
    the Selenium tool internally. The project is hosted on GitHub and downloads
    can be found from PyPI.

    SeleniumLibrary works with Selenium 2.53.6 or newer, including Selenium 3.
    It supports Python 2.7 as well as Python 3.3 or newer. In addition to the
    normal Python interpreter, it works also with PyPy and Jython.
    Unfortunately Selenium is not currently supported by IronPython and thus
    this library does not work with IronPython either.

extra:
  recipe-maintainers:
    - bollwyvl
