travis:
  secure:
    BINSTAR_TOKEN: HTFvNOEuka1EWV7vS1fouqRXWkvcll0oeKUvfubR6pDB5LyvBLykHfrmBcJXa9gVUMu7hR84aI4MFszEdqh/aGUZNU28VhzT/IRZtSXaDiAMK3yiCWZnZiMs9PSTdiHSYtaHM0fq3CrqcMRlTEKPKQ3nEFaNNMc9puMPGzwJV6xXp0fcq7HCoGzxbnzMusArWXa0xSMPofyonTs2xaSS3c7vd9Im4ytpfw71q/L4sdlsj2IrzEzPOXcIx0F+BPt6QPKF46/2Au3xBfKagoOsbJP4/iDvHN+b6/EhccnMIS2tBBmc1c0V88qimSkX5HL0xQJmJuOgUi+NP8rKdK9ZuYf7nncggzWMPyKMhLUxWJc5UUI4LY7hSn7fhW+AqHptkweQTevqMY9LF/lWTePSsPsqmSvK34sy/OvHtkaOSb4VyIokC//64T+wl6oCaxER+efMhXvbCBFtD8/2/dsEqXS2hUUIXw1RE6arFvkyI+I4GjYWhErkkFcqcjfYku36ozgQEra7VmtSgJRnFpFqjC644UL5tX+R+iY4+nN4Zc3UjADydOUUtGo6VMo0wZu6jVxdVcNT5V2WEp6Fb5vz2zm+j8/Yz0bdncPnNqdLqHyJ2yvkWOxxjp082cub7K9f/lyCRmSzIsvb89szrUYg9/AwKQPYWKGjQNZpt2j1p3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
