travis:
  secure:
    BINSTAR_TOKEN: mLDG5jHf7pdGR8BcS08aMBxF6MSjv5ZN2qTi7X6WxYolMtshwWfjKL0jJdRHhu+bvicFrwIA1rWECMX02OazYVKirmw8gQyGhAnO4EQ2iCAqqinUPX2wimho30B6HmGwNgzZuRxRn++HIkTC3t5LekqNGxBYoSiMhdbKoY64olHwXLauRQ2UpbgrnVtmC4CLC/AfD8IL9FkoMt4LB4JQBDGQ9EepP2KuHv4ZGDH+DKHhAxeICgMTsYefZA8Aygr12Pv/hOccCz/30hFOnypwJCZxbikvo/QNFaWfe6dUNVK31Nh0uTfeyCFs+XmtiFqck2ZCQfaQwUKwZx4kiHX46rC4e2XuKDNrBR2tYe8lfP1gfrRHlCrl+nO1UX1EGO+rqyCCM82bdkT42siLcgnEL1IvIBg4ZmDz5AdOtKk48ddJ807Notvn4ArkljYwZykPrfekkHSd9465tfmMzqdZOBpMuygEC1YwVXE4uTrD4M42iqIE/3Ufm8q0WKQP9iv4tPBaQDOr5Pj4Hi3FlrBZ9RP3LDua7C6YsTe8TqQl1TKxKlX+ND2PHrOZ+zeT1D1b/VfWNjbMzabA/Iyd3VFsvHmILXpG+MSkDq3L9o0u+J5Zncjt5WupvrdYhJge7dEBVtH6XlSsAqUtBCjUJkaEIGG5JMeG6tivTXlLpcFW0xI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
